### ISSUE TITLE
Internet Hosting

### ISSUE THREAD

**Issue by gatosyperros** [moonlight-stream/nvidia-gamestream-issues#14]
I'm really confused why I can't post an issue on the internet hosting page.
I have 5 computers, I wanted to access all of them from one Domain.

This is what I get:
https://imgur.com/a/gr53C6E
it tells me that since I already paired one device then all other devices are in conflict uninstall and reboot the router.... 

Port forwarding  a single port would solve most of the issues here, this feels more like a spray 'n pray methode

**Comment by cgutman** [comment]
> I'm really confused why I can't post an issue on the internet hosting page.

People would use it as a forum to get help with their network issues, which isn't what the bug tracker is for. [Discord](https://moonlight-stream.org/discord) is better for that.

> I have 5 computers, I wanted to access all of them from one Domain.
> 
> This is what I get:
> https://imgur.com/a/gr53C6E
> it tells me that since I already paired one device then all other devices are in conflict uninstall and reboot the router....
> 
> Port forwarding a single port would solve most of the issues here, this feels more like a spray 'n pray methode

Port forwarding is fundamentally limited to a single internal IP address per port, because your router only has a single internet-facing IP address. This limitation (and a workaround) is documented in the Limitations section of [release notes](https://github.com/moonlight-stream/Internet-Hosting-Tool/releases) for the Internet Hosting Tool.

You must use IPv6 (which provides unique addresses for each machine behind your router) or a VPN solution like ZeroTier (which creates a virtual LAN where each PC can talk directly to each other) if you would like to stream from multiple PCs behind a single Internet connection.

See the [Internet streaming setup guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet) for more details.

**Comment by gatosyperros** [comment]
I don't think this should be closed.
You have about 65536 ports to chose from,
saying "port forwarding is fundamentally limited to a single internal IP address per port" is kinda misleading.

How could I possibly run 5 server on one IP address with 7 services ranging from a web server, remote service, Moonlight... guess the other? all that from one IP with just a few ports opened, not even on the same computer, but the same public IP!

The "right way" but not flexible way is to allow port forwarding, you could hardcode port 48010 and port 48000, but letting the user chose the port lets people chose  32768 ports to port forwards (assuming port 48000 is used for UDP and TCP).
So in that way your answer is just wrong, you don't need IPv6 to remote into several computers.

**Comment by cgutman** [comment]
> How could I possibly run 5 server on one IP address with 7 services ranging from a web server, remote service, Moonlight... guess the other? all that from one IP with just a few ports opened, not even on the same computer, but the same public IP!

Yes, because they use different ports.

> The "right way" but not flexible way is to allow port forwarding, you could hardcode port 48010 and port 48000, but letting the user chose the port lets people chose 32768 ports to port forwards (assuming port 48000 is used for UDP and TCP).

It's not that easy. I definitely would have provided the option if it was just a matter of a single port.

NVIDIA GameStream uses [8 different ports](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#manual-port-forwarding-advanced), some of which vary by version of GeForce Experience. Not only that, the GameStream protocol doesn't provide a way to determine the other port numbers (particularly external ports, which can and do vary from the internal ports that GFE listens on). And it is not sufficient to just provide a base port and compute other ports based on an offset from the base, because most Carrier Grade NATs do not vend ports in contiguous blocks like that.

Development builds of Moonlight PC and [Sunshine](https://github.com/loki-47-6F-64/sunshine) do have the capability of negotiating alternate ports (and even port forwarding them automatically), because we've designed extensions of the protocol to support that. However, server-side support for this is specific to Sunshine, and not supported by GeForce Experience.

> So in that way your answer is just wrong, you don't need IPv6 to remote into several computers.

I didn't write it out explicitly in my previous response, but perhaps I should have. I meant "if you would like to stream from multiple PCs behind a single Internet connection **using Moonlight**". I definitely don't claim to suggest that IPv6 is the only way to access multiple PCs behind a single Internet connection.
